name: Build Luma3DS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build Luma3DS
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full -y
        sudo apt-get install python python-setuptools python-pip -y
        pip install -U git+https://github.com/TuxSH/firmtool.git
        curl -L https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.17/makerom-v0.17-ubuntu_x86_64.zip -o makerom-v0.17-ubuntu_x86_64.zip
        sudo 7z e makerom-v0.17-ubuntu_x86_64.zip
        sudo chmod +x makerom
        mv makerom /usr/local/bin
        rm makerom-v0.17-ubuntu_x86_64.zip

    - name: Build
      run: |
        make
        mkdir -p ~/result
        cp boot.firm ~/result
    - name: Publish build to GH Actions
      uses: actions/upload-artifact@v2
      with:
        path: ~/result/*
        name: build
